# Generated by Django 4.0.3 on 2022-03-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_bacaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_bacaan', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=1)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('audio_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
